package com.cvilla.medievalia.web;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import com.cvilla.medievalia.dao.ObjetoDAO;
import com.cvilla.medievalia.domain.InstanciaAtributoComplejoDOM;
import com.cvilla.medievalia.domain.InstanciaAtributoSencilloDOM;
import com.cvilla.medievalia.domain.InstanciaObjetoDOM;
import com.cvilla.medievalia.domain.TipoAtributoComplejoDOM;
import com.cvilla.medievalia.domain.TipoObjetoDOM;
import com.cvilla.medievalia.domain.User;
import com.cvilla.medievalia.service.intf.IObjectManager;
import com.cvilla.medievalia.utils.Constants;
 
/**
 * A Spring controller that allows the users to download a PDF document
 * generated by the iText library.
 *
 * @author www.codejava.net
 *
 */

@Controller
public class PdfController {
 
	@Autowired
	private IObjectManager objectManager;

    @RequestMapping(value = "/downloadPDF", method = RequestMethod.GET)
    public ModelAndView downloadExcel(HttpServletRequest request) {
        // create some sample data
        
        HttpSession sesion = request.getSession();
        @SuppressWarnings("unchecked")
        List<InstanciaObjetoDOM> listag = (List<InstanciaObjetoDOM>) sesion.getAttribute("listainforme");
        TipoObjetoDOM tipo = (TipoObjetoDOM) sesion.getAttribute("tipoObjeto");
        List<InstanciaObjetoDOM> listaComp = new ArrayList<InstanciaObjetoDOM>();
		for(InstanciaObjetoDOM io : listag){
			InstanciaObjetoDOM ioc = objectManager.getObjetoDOM(tipo, io.getIdInstancia());
			fillNames(ioc);
			listaComp.add(ioc);
		}
		
		sesion.removeAttribute("listainforme");
		sesion.setAttribute("listainforme",listaComp);
 
        // return a view which will be resolved by an excel view resolver
        return new ModelAndView("pdfView", "listBooks", listag);
    }
    
    private void fillNames(InstanciaObjetoDOM o){
    	for(InstanciaAtributoComplejoDOM iao : o.getAtributosComplejos()){
    		fillNames(iao);
    	}
    }

    private void fillNames(InstanciaAtributoComplejoDOM iao){
    	if(iao.getInstanciaHijo().getTipo().getTipoDOM() == Constants.OBJETO_CNC){
    		InstanciaObjetoDOM n2 = objectManager.getObjetoDOM(iao.getInstanciaHijo().getTipo(), iao.getInstanciaHijo().getNombre());
    		
    		String sub = fill(n2);
    		iao.getInstanciaHijo().setNombre(iao.getInstanciaHijo().getNombre() + sub);
    	}
    	TipoObjetoDOM t = objectManager.getTipoObjetoDOM(iao.getIdTipoObjetoRelacion());
    	if(t != null){
			InstanciaObjetoDOM n3 = objectManager.getObjetoDOM(t, iao.getInstanciaObjetoRelacion().getIdInstancia());
			String sub = fill(n3);
			iao.getInstanciaObjetoRelacion().setNombre(iao.getInstanciaObjetoRelacion().getNombre()+sub);
    	}
    }
    
    private String fill(InstanciaObjetoDOM x){
    	String sub = "";
    	if(x != null){
			for(InstanciaAtributoSencilloDOM ias : x.getAtributosSencillos()){
				if(ias.getIdAtributo() == Constants.OBJETO_ATT_CNC && ias.getValor() != null){
					sub = " ," + ((InstanciaObjetoDOM)ias.getValor()).getNombre();
				}
			}
		}
    	return sub;
    }
}


